<?php

declare(strict_types=1);

namespace Database\Seeders;

final class AdditionalRoadEducationCoursesSeeder extends NextRoadEducationCoursesSeeder
{
    protected function courses(): array
    {
        return [
            [
                'code'=>'EDU-EXP-013','title'=>'Misión Micromovilidad Segura','module_code'=>'MISION-MICROMOVILIDAD','module_title'=>'Misión: Pequeñas ruedas, grandes decisiones',
                'description'=>'Aprende a usar patines, patinetas y otros medios personales con control, protección y respeto por el espacio compartido.',
                'module_summary'=>'Tres retos para preparar el equipo, dominar el movimiento y convivir con personas peatonas.',
                'objectives'=>'Comprobar equipo y entorno; controlar velocidad y detención; elegir espacios permitidos y ceder prioridad a quienes caminan.',
                'prerequisites'=>'Las prácticas se realizan en espacios permitidos, planos y sin tránsito, con supervisión adulta cuando corresponda.',
                'competency'=>'MICROMOVILIDAD-SEGURA','competency_title'=>'Usa micromovilidad con control y convivencia','competency_description'=>'Prepara, controla y adapta medios personales de movilidad al entorno compartido.','subcompetency'=>'MICRO.CONTROLA',
                'prompt'=>'¿Qué decisión conserva control y protege a las personas alrededor?',
                'units'=>[
                    ['code'=>'MICRO-PREPARA','title'=>'Equipo y espacio antes de rodar','summary'=>'Revisá protección, superficie y límites.','objective'=>'Comprobar equipo, ajuste y zona segura antes de iniciar.','indicator'=>'MICRO.PREPARA','lesson_title'=>'Antes de impulsarte, preparate','content'=>'Casco bien ajustado, calzado cerrado y protecciones acordes reducen lesiones, pero no eliminan el riesgo. También se revisan ruedas, frenos, superficie, iluminación y reglas del lugar. Un juguete con ruedas puede alcanzar velocidad suficiente para perder el control.','scenarios'=>[['Casco flojo','El casco se mueve y la correa queda lejos de la barbilla.','Ajustarlo antes de iniciar y pedir ayuda si no queda estable','Usarlo así porque el recorrido será corto','Correcto. La protección debe permanecer en posición.'],['Pendiente desconocida','Una niña quiere estrenar patines bajando una cuesta.','Practicar primero equilibrio y frenado en una zona plana','Usar la cuesta para aprender más rápido','Correcto. La dificultad se aumenta solo después de demostrar control.']],'practice'=>'Construí una revisión de cinco puntos: cuerpo, casco, ruedas, superficie y zona de detención.'],
                    ['code'=>'MICRO-CONTROLA','title'=>'Impulsar, girar y detenerse','summary'=>'Dominá el movimiento antes de compartir espacio.','objective'=>'Regular velocidad y realizar una detención controlada.','indicator'=>'MICRO.CONTROLA','lesson_title'=>'Control antes que velocidad','content'=>'El dominio básico incluye postura estable, mirada hacia la trayectoria, impulso progresivo, giro amplio y detención sin usar personas u objetos como freno. Si aumenta la cantidad de gente, se reduce velocidad o se camina llevando el equipo.','scenarios'=>[['Pelota inesperada','Una pelota cruza la trayectoria durante la práctica.','Frenar con la técnica practicada y mantener distancia','Girar bruscamente hacia donde haya espacio','Correcto. Una velocidad controlada permite detenerse sin trasladar el riesgo.'],['Zona concurrida','Muchas personas ocupan el paso compartido.','Bajarse y llevar el equipo hasta una zona despejada','Tocar una señal y abrirse paso','Correcto. Quien se desplaza más rápido protege a quien camina.']],'practice'=>'En un espacio cerrado al tránsito, marcá salida, giro y detención. Lográ tres detenciones estables antes de aumentar dificultad.'],
                    ['code'=>'MICRO-CONVIVE','title'=>'Compartir sin sorprender','summary'=>'Cedé, comunicá y elegí el lugar correcto.','objective'=>'Adaptar la micromovilidad a normas, personas y condiciones del espacio.','indicator'=>'MICRO.CONVIVE','lesson_title'=>'El espacio compartido no es una pista','content'=>'Las reglas sobre micromovilidad varían según lugar y dispositivo. Siempre se verifica dónde está permitido usarlo. Cerca de accesos, niñas pequeñas, personas mayores, animales o personas con discapacidad, se baja la velocidad y se evita pasar de cerca.','scenarios'=>[['Salida de comercio','Una puerta oculta a quienes salen hacia el paso.','Reducir hasta poder detenerse y dejar separación lateral','Acelerar para pasar antes de que alguien salga','Correcto. Una zona ciega exige velocidad de detención inmediata.'],['Paso peatonal','El recorrido cruza una zona destinada a peatones.','Bajarse si corresponde y ceder completamente el paso','Cruzar zigzagueando entre personas','Correcto. La prioridad peatonal guía la decisión.']],'practice'=>'Diseñá un código de convivencia con cinco acuerdos y registrá una demostración acompañada en el Pasaporte Vial.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-014','title'=>'Misión Caminos Rurales y Fauna','module_code'=>'MISION-RURAL-FAUNA','module_title'=>'Misión: Anticipar en caminos vivos',
                'description'=>'Decisiones seguras en caminos rurales con curvas, superficies variables, maquinaria, animales y conectividad limitada.',
                'module_summary'=>'Tres retos para leer el camino, convivir con fauna y preparar rutas con menos servicios.',
                'objectives'=>'Interpretar superficie y visibilidad; responder sin violencia ante animales; planear comunicación y alternativas en zonas rurales.',
                'prerequisites'=>'Aplica a todos los modos. Las personas menores observan y practican únicamente con acompañamiento.',
                'competency'=>'MOVILIDAD-RURAL','competency_title'=>'Se desplaza con criterio en entornos rurales','competency_description'=>'Adapta velocidad, distancia y planificación a caminos rurales y presencia de animales.','subcompetency'=>'RURAL.ANTICIPA',
                'prompt'=>'¿Qué decisión protege la vida ante una condición rural cambiante?',
                'units'=>[
                    ['code'=>'RURAL-LEE','title'=>'Leer superficie y visibilidad','summary'=>'Observá curvas, polvo, barro y tránsito especial.','objective'=>'Adaptar el movimiento a superficie irregular y visibilidad limitada.','indicator'=>'RURAL.LEE','lesson_title'=>'El camino informa antes del peligro','content'=>'En caminos rurales pueden cambiar el ancho, la adherencia y la visibilidad en pocos metros. Curvas, vegetación, polvo, puentes angostos y maquinaria agrícola exigen reducir antes, mantener distancia y evitar asumir que el camino está libre.','scenarios'=>[['Curva con polvo','Un vehículo adelante levanta polvo y oculta la trayectoria.','Aumentar distancia y reducir hasta recuperar visión','Adelantar para salir de la nube','Correcto. Sin visión no existe información suficiente para adelantar.'],['Puente angosto','Dos vehículos se aproximan a un paso de un solo carril.','Reducir, comunicar y respetar la prioridad segura','Acelerar para llegar primero','Correcto. Coordinar evita quedar atrapados en el estrechamiento.']],'practice'=>'Analizá un recorrido rural conocido en un mapa: marcá tres puntos de visibilidad reducida y un lugar seguro de espera.'],
                    ['code'=>'RURAL-FAUNA','title'=>'Animales en la vía','summary'=>'Reducí, esperá y evitá respuestas agresivas.','objective'=>'Responder de forma gradual y predecible ante fauna o animales domésticos.','indicator'=>'RURAL.FAUNA','lesson_title'=>'La fauna no interpreta el tránsito como nosotros','content'=>'Un animal puede detenerse, regresar o moverse de forma inesperada. Se reduce con anticipación, se evita la bocina agresiva y se conserva distancia. No se persigue, alimenta ni intenta capturar fauna silvestre; se reporta la situación a personas competentes cuando sea necesario.','scenarios'=>[['Ganado cruzando','Varios animales ocupan el camino guiados por una persona.','Detenerse a distancia y seguir las indicaciones del responsable','Pasar entre los animales lentamente','Correcto. Separar el grupo puede provocar movimientos impredecibles.'],['Animal silvestre','Un animal aparece al borde durante la noche.','Reducir de manera controlada y darle espacio para retirarse','Acercarse para fotografiarlo','Correcto. Distancia y calma protegen a personas y fauna.']],'practice'=>'Creá una secuencia ilustrada: detectar, reducir, detener si hace falta, esperar y continuar solo con espacio suficiente.'],
                    ['code'=>'RURAL-PLANEA','title'=>'Ruta, comunicación y plan B','summary'=>'Prepará el viaje cuando hay menos servicios.','objective'=>'Planificar recursos, comunicación y alternativas sin depender de conectividad continua.','indicator'=>'RURAL.PLANEA','lesson_title'=>'Prepararse cuando la señal desaparece','content'=>'Antes de una ruta remota se comparten destino y horario aproximado, se revisan clima, combustible o energía, estado del medio y puntos seguros. El mapa sin conexión y los contactos necesarios se preparan antes; conducir nunca se combina con manipular el teléfono.','scenarios'=>[['Sin cobertura','La aplicación deja de actualizar la ruta en un cruce desconocido.','Detenerse en un lugar seguro y consultar el plan descargado','Continuar al azar mientras vuelve la señal','Correcto. Resolver la orientación requiere salir primero del movimiento.'],['Lluvia en aumento','Un camino sin pavimentar comienza a acumular agua.','Regresar o usar una alternativa confirmada antes de quedar aislado','Continuar porque falta poco','Correcto. El plan cambia antes de que desaparezca la salida segura.']],'practice'=>'Prepará una tarjeta de ruta sin datos privados públicos: destino general, contactos, puntos seguros, clima y criterio de regreso.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-015','title'=>'Misión Comunidad Vial Activa','module_code'=>'MISION-COMUNIDAD-ACTIVA','module_title'=>'Misión: Observar, proponer y transformar',
                'description'=>'Herramientas para que estudiantes, familias y comunidades mejoren su entorno vial con evidencia y colaboración.',
                'module_summary'=>'Tres retos para observar sin exponerse, priorizar problemas y construir acuerdos verificables.',
                'objectives'=>'Recolectar observaciones seguras; priorizar riesgos con criterios; proponer y evaluar pequeñas mejoras comunitarias.',
                'prerequisites'=>'No autoriza intervenir señales, dirigir tránsito ni ingresar a la calzada. Toda observación de menores requiere acompañamiento.',
                'competency'=>'PARTICIPACION-VIAL','competency_title'=>'Participa en mejoras viales comunitarias','competency_description'=>'Observa, prioriza y propone mejoras con evidencia, respeto y seguimiento.','subcompetency'=>'COMUNIDAD.TRANSFORMA',
                'prompt'=>'¿Qué acción convierte una preocupación en una mejora segura y colaborativa?',
                'units'=>[
                    ['code'=>'COMUNIDAD-OBSERVA','title'=>'Observar sin exponerse','summary'=>'Separá hechos, interpretaciones y datos privados.','objective'=>'Registrar condiciones viales desde un lugar protegido y con datos pertinentes.','indicator'=>'COMUNIDAD.OBSERVA','lesson_title'=>'Una observación que sí ayuda','content'=>'Una observación útil describe lugar general, momento, conducta o condición visible y quién podría verse afectado. No requiere rostros, placas ni confrontaciones. Se observa desde un espacio protegido y nunca se entra a la vía para obtener una mejor imagen.','scenarios'=>[['Vehículo bloqueando','Un vehículo ocupa frecuentemente una rampa escolar.','Registrar la condición sin datos personales y usar el canal responsable','Fotografiar de cerca a la persona y publicarla','Correcto. La evidencia describe el problema sin exponer ni confrontar.'],['Cruce peligroso','Para ver mejor habría que situarse en la calzada.','Observar desde protección o descartar ese punto','Entrar unos segundos con una persona vigilando','Correcto. Ninguna medición justifica crear exposición.']],'practice'=>'Hacé una ficha ficticia con hecho observable, usuarios afectados, frecuencia aproximada y condición protectora ausente.'],
                    ['code'=>'COMUNIDAD-PRIORIZA','title'=>'Elegir qué atender primero','summary'=>'Compará gravedad, exposición y posibilidad de mejora.','objective'=>'Priorizar riesgos sin basarse únicamente en opiniones o popularidad.','indicator'=>'COMUNIDAD.PRIORIZA','lesson_title'=>'Lo urgente no siempre es lo más ruidoso','content'=>'Priorizar combina severidad posible, frecuencia de exposición, cantidad y vulnerabilidad de personas, y viabilidad de una acción segura. Escuchar distintas experiencias evita que solo se atienda a quien habla más fuerte.','scenarios'=>[['Dos propuestas','Una mejora estética compite con liberar un cruce usado diariamente por escolares.','Priorizar el cruce por exposición y vulnerabilidad documentadas','Elegir la propuesta con más reacciones en redes','Correcto. Los criterios transparentes orientan recursos hacia mayor protección.'],['Una sola visita','El grupo vio una conducta riesgosa una vez.','Contrastar momentos y fuentes antes de afirmar que es frecuente','Presentarla como un patrón confirmado','Correcto. Diferenciar evento y patrón mejora la calidad de la decisión.']],'practice'=>'Usá una matriz sencilla del 1 al 3 para gravedad, exposición, vulnerabilidad y factibilidad; explicá el resultado.'],
                    ['code'=>'COMUNIDAD-ACTUA','title'=>'Proponer, probar y aprender','summary'=>'Definí responsables, plazo e indicador.','objective'=>'Diseñar una acción pequeña, segura, medible y revisable.','indicator'=>'COMUNIDAD.ACTUA','lesson_title'=>'Una propuesta necesita seguimiento','content'=>'Una mejora comunitaria define problema, acción, responsable competente, plazo e indicador observable. Puede comenzar con acuerdos de entrada escolar, despeje de visibilidad o campañas educativas. La comunidad no altera infraestructura ni señalización por cuenta propia.','scenarios'=>[['Señal deteriorada','El grupo quiere pintar una señal pública para arreglarla.','Documentar y canalizar la solicitud a la autoridad responsable','Intervenirla durante el fin de semana','Correcto. La participación respeta responsabilidades técnicas y legales.'],['Campaña realizada','Se entregaron mensajes sobre cruces seguros.','Observar después si cambió la conducta acordada y ajustar','Declarar éxito por cantidad de folletos','Correcto. El impacto se evalúa en conductas o condiciones, no solo productos.']],'practice'=>'Creá una micropropuesta con problema, acción, aliado, plazo, indicador y revisión. Guardala como proyecto en tu Pasaporte Vial.'],
                ],
            ],
        ];
    }
}
