<?php

declare(strict_types=1);

namespace Database\Seeders;

final class FifthRoadEducationCoursesSeeder extends NextRoadEducationCoursesSeeder
{
    protected function courses(): array
    {
        return [
            [
                'code'=>'EDU-EXP-022','title'=>'Misión Vehículos Grandes y Puntos Ciegos','module_code'=>'MISION-PUNTOS-CIEGOS','module_title'=>'Misión: Ver el espacio que la otra persona no ve',
                'description'=>'Aprende a reconocer puntos ciegos, giros amplios y distancias de detención de autobuses, camiones y maquinaria.',
                'module_summary'=>'Tres retos para detectar zonas invisibles, anticipar trayectorias amplias y mantener separación.',
                'objectives'=>'Identificar puntos ciegos; evitar ubicaciones atrapadas durante giros; conservar distancia frente a vehículos grandes detenidos o en movimiento.',
                'prerequisites'=>'Aplica a peatones, ciclistas, motociclistas y conductores. Las prácticas son simuladas y nunca se realizan junto a maquinaria activa.',
                'competency'=>'CONVIVENCIA-VEHICULO-GRANDE','competency_title'=>'Convive con vehículos grandes sin entrar en zonas invisibles','competency_description'=>'Reconoce limitaciones de visibilidad y movimiento de vehículos grandes.','subcompetency'=>'VEHICULOGRANDE.ANTICIPA',
                'prompt'=>'¿Qué posición conserva visibilidad, separación y una ruta de escape?',
                'units'=>[
                    ['code'=>'GRANDE-VISIBILIDAD','title'=>'Si no ves, podrían no verte','summary'=>'Reconocé zonas laterales, traseras y frontales invisibles.','objective'=>'Identificar puntos ciegos y salir de ellos sin movimientos repentinos.','indicator'=>'VEHICULO_GRANDE.VISIBILIDAD','lesson_title'=>'Un vehículo grande no ve todo a su alrededor','content'=>'La altura, longitud y estructura crean zonas que espejos y cámaras no eliminan por completo. Permanecer junto a cabina, costados o parte trasera aumenta el riesgo. El contacto visual puede aportar información, pero nunca garantiza que te hayan visto.','scenarios'=>[['Bicicleta junto al autobús','Una bicicleta queda al lado derecho de un autobús detenido en una esquina.','Permanecer detrás con separación y no avanzar junto al giro','Subir hasta la ventana para ser visible','Correcto. Evitar el costado impide quedar atrapado por el giro.'],['Niña frente a camión','Una niña cruza muy cerca del frente de un camión estacionado.','Buscar un cruce visible y alejado con acompañamiento','Cruzar rápido antes de que arranque','Correcto. Alejarse permite ver y ser vista.']],'practice'=>'En una maqueta, marcá zonas de visibilidad probable y rutas que evitan pasar cerca del vehículo.'],
                    ['code'=>'GRANDE-TRAYECTORIA','title'=>'El giro ocupa más espacio','summary'=>'Observá dirección, ruedas y separación disponible.','objective'=>'Anticipar giros amplios y movimientos de remolques.','indicator'=>'VEHICULO_GRANDE.TRAYECTORIA','lesson_title'=>'La parte trasera no sigue exactamente a la delantera','content'=>'En un giro, ruedas traseras pueden acercarse más al borde y otras partes desplazarse hacia afuera. Direccionales, posición y orientación de ruedas son pistas, no invitaciones a pasar. Nunca se entra entre un vehículo grande y el borde.','scenarios'=>[['Camión girando','Un camión abre su trayectoria antes de girar.','Mantener distancia y esperar a que complete toda la maniobra','Pasar por el espacio que abrió','Correcto. Ese espacio forma parte de la trayectoria del giro.'],['Remolque en curva','La parte trasera se aproxima al carril vecino.','Reducir y darle espacio lateral y longitudinal','Mantenerse a la par para que conserve su carril','Correcto. La separación evita una zona de barrido.']],'practice'=>'Dibujá la huella de un giro amplio y explicá por qué el espacio temporalmente vacío no está disponible.'],
                    ['code'=>'GRANDE-DISTANCIA','title'=>'Más masa necesita más margen','summary'=>'Evitá cruzar cerca o incorporarte sin espacio.','objective'=>'Conservar distancia considerando detención y visión limitada.','indicator'=>'VEHICULO_GRANDE.DISTANCIA','lesson_title'=>'La distancia protege a ambos','content'=>'Vehículos grandes requieren más espacio para detenerse y pueden ocultar personas o señales. No se cruza inmediatamente delante o detrás de ellos. Al incorporarse, se deja una distancia que no obligue a frenar bruscamente.','scenarios'=>[['Autobús detenido','Un autobús oculta el carril opuesto en una parada.','Esperar y cruzar desde un lugar con visión completa','Cruzar pegado al frente para reducir distancia','Correcto. Separarse recupera información de ambos sentidos.'],['Ingreso cercano','Hay un espacio corto delante de un camión en movimiento.','Esperar una separación mayor y entrar de forma progresiva','Ingresar porque el camión circula lento','Correcto. La velocidad baja no elimina su distancia de detención.']],'practice'=>'Creá tres reglas personales: dónde esperar, cuándo no adelantar y cómo recuperar visión alrededor de un vehículo grande.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-023','title'=>'Misión Estacionamientos y Maniobras Seguras','module_code'=>'MISION-ESTACIONAMIENTO-SEGURO','module_title'=>'Misión: Baja velocidad, máxima atención',
                'description'=>'Aprende a caminar, acompañar y maniobrar en estacionamientos, entradas y zonas de reversa.',
                'module_summary'=>'Tres retos para leer trayectorias, proteger a personas pequeñas y ejecutar maniobras sin depender solo de sensores.',
                'objectives'=>'Detectar vehículos que podrían moverse; organizar acompañamiento seguro; detener y reiniciar maniobras cuando se pierde información.',
                'prerequisites'=>'Las prácticas de conducción requieren autorización y supervisión apropiadas. Niñas y niños practican como peatones acompañados.',
                'competency'=>'MANIOBRA-BAJA-VELOCIDAD','competency_title'=>'Gestiona espacios de maniobra a baja velocidad','competency_description'=>'Observa trayectorias ocultas y mantiene control durante estacionamiento y reversa.','subcompetency'=>'MANIOBRA.PROTEGE',
                'prompt'=>'¿Qué decisión mantiene visibles a las personas y controlada la trayectoria?',
                'units'=>[
                    ['code'=>'PARQUEO-OBSERVA','title'=>'Un vehículo estacionado puede moverse','summary'=>'Buscá luces, ruedas, sonido y personas dentro escondidas.','objective'=>'Reconocer pistas de movimiento y zonas de visibilidad limitada.','indicator'=>'MANIOBRA.OBSERVA','lesson_title'=>'Las filas de vehículos ocultan trayectorias','content'=>'Luces de reversa, motor, ruedas giradas o una persona dentro son pistas. También pueden aparecer niñas, carritos, sillas de ruedas o animales entre vehículos. Se camina por rutas definidas, sin correr ni usar el teléfono.','scenarios'=>[['Luz de reversa','Un vehículo enciende luces mientras una familia pasa detrás.','Detenerse fuera de la trayectoria y confirmar que la persona conductora los percibió','Continuar porque los peatones tienen prioridad','Correcto. La prioridad no reemplaza hacerse visible y esperar.'],['Pelota entre autos','Una pelota rueda hacia una fila estacionada.','Detenerse y pedir ayuda adulta sin correr detrás','Seguirla antes de que pase un vehículo','Correcto. Un objeto no justifica entrar en una zona oculta.']],'practice'=>'Observá una ilustración y marcá cinco pistas de movimiento y cuatro lugares donde podría aparecer alguien.'],
                    ['code'=>'PARQUEO-ACOMPANA','title'=>'Personas pequeñas siempre visibles','summary'=>'Definí punto de espera, contacto y orden de movimiento.','objective'=>'Acompañar a niñas, niños y personas que requieren apoyo durante maniobras.','indicator'=>'MANIOBRA.ACOMPANA','lesson_title'=>'Primero se ubican las personas, luego se mueve el vehículo','content'=>'Antes de maniobrar se confirma dónde está cada persona. Niñas y niños esperan con una persona adulta en un punto visible, nunca detrás o delante del vehículo. Equipaje y puertas se resuelven antes de iniciar el movimiento.','scenarios'=>[['Salida familiar','Una persona adulta acomoda equipaje mientras una niña espera detrás del vehículo.','Mover a la niña a un punto visible con supervisión antes de continuar','Pedirle que avise si se acerca otro auto','Correcto. Una niña no debe administrar el riesgo de una maniobra.'],['Entrada estrecha','Una persona guía desde un lugar donde quien conduce no puede verla.','Detenerse y reubicarla en una posición visible y acordada','Continuar siguiendo su voz','Correcto. Si se pierde contacto, la maniobra se detiene.']],'practice'=>'Diseñá un acuerdo familiar: punto seguro, persona responsable, señal de alto y confirmación antes de mover.'],
                    ['code'=>'PARQUEO-MANIOBRA','title'=>'Sensores ayudan, no reemplazan mirar','summary'=>'Movete despacio y detenete ante cualquier duda.','objective'=>'Ejecutar o supervisar una maniobra con observación completa y pausas.','indicator'=>'MANIOBRA.CONTROLA','lesson_title'=>'La maniobra se reinicia cuando cambia la escena','content'=>'Cámaras y sensores tienen límites por suciedad, ángulo u objetos pequeños. Antes y durante la reversa se observan espejos, entorno y trayectoria directa; se avanza a velocidad mínima. Si desaparece una persona o surge una distracción, se detiene por completo.','scenarios'=>[['Alarma del sensor','El sensor no suena, pero una bicicleta quedó cerca de una esquina.','Detenerse y comprobar visualmente antes de continuar','Confiar en el silencio del sistema','Correcto. La ayuda electrónica no garantiza una zona libre.'],['Interrupción durante reversa','Llega una llamada mientras el vehículo retrocede.','Detener completamente y resolver solo fuera de la maniobra','Responder con manos libres mientras termina','Correcto. Una maniobra estrecha requiere toda la atención.']],'practice'=>'Ordená el protocolo: inspeccionar, ubicar personas, ajustar, señalizar, mover despacio, detener ante duda y verificar al finalizar.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-024','title'=>'Misión Viajes y Rutas Desconocidas','module_code'=>'MISION-RUTA-DESCONOCIDA','module_title'=>'Misión: Explorar sin improvisar la seguridad',
                'description'=>'Prepara viajes, excursiones y recorridos turísticos en lugares cuyas reglas, clima o infraestructura no conoces.',
                'module_summary'=>'Tres retos para investigar antes, orientarse durante el viaje y adaptarse sin asumir que todo funciona igual.',
                'objectives'=>'Preparar información esencial; reconocer diferencias locales; conservar comunicación, descanso y alternativas durante un recorrido nuevo.',
                'prerequisites'=>'Para familias, centros educativos y personas viajeras. No sustituye información oficial local ni supervisión de actividades especializadas.',
                'competency'=>'RUTA-DESCONOCIDA','competency_title'=>'Planifica movilidad segura en entornos desconocidos','competency_description'=>'Investiga, verifica y adapta recorridos nuevos sin perder protección.','subcompetency'=>'VIAJE.PLANEA',
                'prompt'=>'¿Qué decisión transforma lo desconocido en un recorrido preparado?',
                'units'=>[
                    ['code'=>'VIAJE-INVESTIGA','title'=>'Conocer antes de llegar','summary'=>'Revisá normas, clima, transporte y accesibilidad.','objective'=>'Preparar información confiable y necesidades del grupo.','indicator'=>'VIAJE.INVESTIGA','lesson_title'=>'Una ruta nueva comienza antes del viaje','content'=>'Se consultan fuentes oficiales sobre normas, cierres, transporte, clima y emergencias. También se consideran edades, accesibilidad, medicamentos personales, descansos y formas de contacto. Una recomendación viral no sustituye información vigente.','scenarios'=>[['Video turístico','Un video recomienda un atajo, pero no muestra fecha ni condiciones.','Confirmar con una fuente actual y preparar otra ruta','Usarlo porque muchas personas lo compartieron','Correcto. Popularidad no equivale a vigencia ni seguridad.'],['Grupo diverso','La ruta incluye una caminata larga sin zonas de descanso.','Adaptarla a la capacidad y necesidades de todo el grupo','Mantenerla y pedir que cada persona avance a su ritmo','Correcto. La planificación integra al grupo antes de salir.']],'practice'=>'Creá una ficha previa: reglas locales, clima, accesibilidad, transporte, contactos, horarios y plan alterno.'],
                    ['code'=>'VIAJE-ORIENTA','title'=>'Orientarse sin distraerse','summary'=>'Definí puntos de encuentro y resolvé dudas fuera del flujo.','objective'=>'Mantener unido y comunicado al grupo durante la navegación.','indicator'=>'VIAJE.ORIENTA','lesson_title'=>'Perderse no obliga a decidir en movimiento','content'=>'El grupo acuerda responsables, punto de encuentro y qué hacer si se separa. La navegación se consulta en un lugar protegido. Se evita seguir a desconocidos o cruzar impulsivamente para no perder al grupo. Niñas y niños conocen una identificación y contacto seguro apropiados.','scenarios'=>[['Giro perdido','El grupo pasó la entrada correcta en una calle concurrida.','Continuar hasta un lugar seguro y reconstruir la ruta','Cruzar inmediatamente para regresar','Correcto. Corregir tarde y con calma es más seguro que una reacción brusca.'],['Persona separada','Una niña no ve al grupo en una terminal.','Permanecer en el punto acordado y pedir ayuda a personal identificado','Salir de la terminal para buscar el vehículo','Correcto. El acuerdo previo reduce desplazamientos impredecibles.']],'practice'=>'Ensayá un plan de separación con punto, contacto, persona autorizada y datos que nunca deben compartirse públicamente.'],
                    ['code'=>'VIAJE-ADAPTA','title'=>'Las reglas y el entorno pueden cambiar','summary'=>'Observá antes de transferir costumbres conocidas.','objective'=>'Adaptar conductas a señalización, clima y cultura vial local sin perder principios universales.','indicator'=>'VIAJE.ADAPTA','lesson_title'=>'Lo familiar no siempre funciona igual','content'=>'Sentido de circulación, prioridad, transporte y señalización pueden variar. Antes de actuar se observa el patrón, se siguen controles locales y se pregunta a fuentes autorizadas. Los principios universales permanecen: atención, margen, previsibilidad y protección de personas vulnerables.','scenarios'=>[['Cruce diferente','La señalización funciona de una manera que el grupo no reconoce.','Esperar, observar y confirmar con información local','Imitar de inmediato a la primera persona','Correcto. Una observación aislada no explica la regla.'],['Clima extremo','El itinerario continúa aunque una alerta oficial desaconseja el trayecto.','Cambiar o suspender el plan y comunicarlo','Continuar porque las reservas no son reembolsables','Correcto. Un costo no convierte una exposición en aceptable.']],'practice'=>'Compará origen y destino con cuatro columnas: qué cambia, qué fuente lo confirma, cómo adaptarse y qué principio universal se mantiene.'],
                ],
            ],
        ];
    }
}
