<?php

declare(strict_types=1);

namespace Database\Seeders;

final class FourthRoadEducationCoursesSeeder extends NextRoadEducationCoursesSeeder
{
    protected function courses(): array
    {
        return [
            [
                'code'=>'EDU-EXP-019','title'=>'Misión Vehículo en Condiciones Seguras','module_code'=>'MISION-VEHICULO-SEGURO','module_title'=>'Misión: Revisar, detectar y decidir',
                'description'=>'Aprende a comprobar condiciones básicas de bicicletas, motocicletas y automóviles antes de iniciar un recorrido.',
                'module_summary'=>'Tres retos para revisar el medio, reconocer cambios y detener el uso cuando falta seguridad.',
                'objectives'=>'Realizar una revisión previa; interpretar alertas y cambios observables; comunicar y retirar de servicio un medio inseguro.',
                'prerequisites'=>'No sustituye mantenimiento técnico. Las personas menores revisan bicicletas y equipos únicamente con acompañamiento.',
                'competency'=>'CONDICION-VEHICULAR','competency_title'=>'Comprueba condiciones seguras del medio de transporte','competency_description'=>'Detecta cambios observables y evita iniciar o continuar con condiciones inseguras.','subcompetency'=>'VEHICULO.COMPRUEBA',
                'prompt'=>'¿Qué decisión evita convertir una condición mecánica en un riesgo vial?',
                'units'=>[
                    ['code'=>'VEHICULO-REVISA','title'=>'Una vuelta antes de salir','summary'=>'Observá ruedas, luces, controles y elementos sueltos.','objective'=>'Aplicar una revisión previa apropiada al medio de transporte.','indicator'=>'VEHICULO.REVISA','lesson_title'=>'La revisión más útil ocurre antes del movimiento','content'=>'Cada medio necesita una lista apropiada. En bicicleta se observan frenos, ruedas, cadena, dirección y luces. En vehículos motorizados también se comprueban neumáticos, luces, testigos, visibilidad, fluidos evidentes y carga. Revisar no significa reparar sin conocimiento.','scenarios'=>[['Neumático diferente','Una rueda luce mucho más baja que las demás.','No iniciar y solicitar una comprobación adecuada','Conducir despacio hasta una estación','Correcto. El trayecto no debe usarse como prueba de una condición dudosa.'],['Luz de bicicleta','La luz trasera no enciende antes de volver al anochecer.','Resolver la visibilidad o cambiar el plan','Salir por calles con más iluminación','Correcto. La iluminación exterior no reemplaza ser visible.']],'practice'=>'Creá una revisión de seis puntos para el medio que usás y practicá el orden sin entrar en una vía activa.'],
                    ['code'=>'VEHICULO-DETECTA','title'=>'Cambios que piden atención','summary'=>'Escuchá, sentí y observá sin diagnosticar a ciegas.','objective'=>'Reconocer señales de cambio y responder sin improvisar reparaciones.','indicator'=>'VEHICULO.DETECTA','lesson_title'=>'Un ruido nuevo es información','content'=>'Vibraciones, olores, ruidos, testigos o cambios al frenar y dirigir requieren atención. Se evita continuar hasta que la falla sea grave. La respuesta segura es reducir gradualmente, salir del flujo hacia un lugar permitido y pedir revisión competente.','scenarios'=>[['Vibración creciente','El volante o manillar comienza a vibrar de forma inusual.','Reducir sin maniobras bruscas y detenerse en un lugar seguro','Acelerar para comprobar si desaparece','Correcto. Un cambio nuevo requiere retirar exposición y evaluar.'],['Olor desconocido','Aparece un olor fuerte acompañado de humo leve.','Detenerse de forma segura, alejarse y pedir asistencia','Abrir de inmediato componentes calientes','Correcto. La distancia evita exposición a fuego, vapores o piezas calientes.']],'practice'=>'Clasificá alertas ficticias en observar, detener de forma segura o pedir asistencia inmediata; justificá cada elección.'],
                    ['code'=>'VEHICULO-DECIDE','title'=>'Retirar de servicio también protege','summary'=>'Comunicá la condición y evitá que otra persona herede el riesgo.','objective'=>'Impedir el uso de un medio inseguro y documentar la incidencia.','indicator'=>'VEHICULO.DECIDE','lesson_title'=>'La prisa no repara una falla','content'=>'Si una condición compromete control, visibilidad o protección, el medio no se usa hasta recibir la atención necesaria. Se comunica claramente, se identifica sin crear otro peligro y se registra qué se observó, no un diagnóstico inventado.','scenarios'=>[['Vehículo compartido','Terminó tu turno y el freno respondió de forma irregular.','Reportar y evitar que vuelva a usarse hasta revisión','Entregarlo y mencionarlo si la otra persona pregunta','Correcto. El riesgo compartido requiere comunicación explícita.'],['Bicicleta escolar','Una pieza del manillar queda floja antes de una práctica.','Suspender la práctica y entregarla a una persona competente','Apretarla a mano y probar en movimiento','Correcto. El control de dirección no admite una prueba improvisada.']],'practice'=>'Redactá una tarjeta de incidencia: medio, cambio observado, momento, decisión tomada y revisión requerida.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-020','title'=>'Misión Cruces Ferroviarios Seguros','module_code'=>'MISION-CRUCE-FERROVIARIO','module_title'=>'Misión: Nunca competir con el tren',
                'description'=>'Aprende a reconocer, esperar y liberar completamente los cruces ferroviarios como peatón, ciclista, pasajero o conductor.',
                'module_summary'=>'Tres retos para detectar el cruce, respetar el cierre y evitar quedar atrapado sobre la vía férrea.',
                'objectives'=>'Reconocer señales ferroviarias; detenerse ante cualquier indicación de aproximación; confirmar espacio de salida antes de cruzar.',
                'prerequisites'=>'Basado en principios universales y el contexto ferroviario costarricense. Las prácticas son simuladas y alejadas de vías activas.',
                'competency'=>'CRUCE-FERROVIARIO','competency_title'=>'Atraviesa cruces ferroviarios con margen','competency_description'=>'Reconoce el riesgo ferroviario, espera y cruza únicamente con salida completa.','subcompetency'=>'FERROCARRIL.CRUZA',
                'prompt'=>'¿Qué decisión garantiza que la trayectoria ferroviaria permanezca libre?',
                'units'=>[
                    ['code'=>'TREN-RECONOCE','title'=>'Detectar antes de llegar','summary'=>'Buscá señales, marcas, luces y espacio disponible.','objective'=>'Reconocer anticipadamente un cruce ferroviario y preparar la detención.','indicator'=>'FERROCARRIL.RECONOCE','lesson_title'=>'Las vías anuncian un conflicto diferente','content'=>'Un tren necesita gran distancia para detenerse y puede parecer más lento o lejano de lo que está. Señales, marcas, luces, sonido y barreras exigen atención. Se retiran audífonos y distracciones antes de aproximarse.','scenarios'=>[['Audífonos al caminar','Una persona se acerca a las vías sin escuchar el entorno.','Detenerse en zona segura, retirar la distracción y observar','Cruzar siguiendo a la persona de adelante','Correcto. Cada persona confirma el cruce por sí misma.'],['Tren lejano','El tren se ve pequeño y parece avanzar lentamente.','Esperar sin intentar calcular una carrera','Cruzar porque todavía hay distancia','Correcto. La percepción visual no permite competir con seguridad.']],'practice'=>'En una maqueta, identificá zona de aproximación, lugar de espera, trayectoria ferroviaria y salida completa.'],
                    ['code'=>'TREN-ESPERA','title'=>'Una barrera nunca se rodea','summary'=>'Esperá todas las indicaciones de reapertura.','objective'=>'Mantenerse fuera del cruce durante señales activas o barreras cerradas.','indicator'=>'FERROCARRIL.ESPERA','lesson_title'=>'Después de un tren puede venir otro','content'=>'Luces, alarma, barrera o indicación autorizada significan detenerse fuera de la trayectoria. Nunca se rodea una barrera ni se cruza inmediatamente detrás del último vagón: puede existir otro tren o continuar activo el control.','scenarios'=>[['Barrera descendiendo','La barrera comienza a bajar cuando alguien se aproxima.','Detenerse antes de la zona de cierre','Acelerar para pasar antes de que termine','Correcto. El inicio del cierre elimina la opción de cruzar.'],['Pasó el tren','El último vagón pasó, pero las luces siguen activas.','Continuar esperando hasta la reapertura completa','Cruzar porque la vía visible está libre','Correcto. El sistema puede advertir otro movimiento.']],'practice'=>'Ordená la secuencia: aproximarse, detenerse, esperar reapertura, observar ambos sentidos y cruzar sin detenerse.'],
                    ['code'=>'TREN-LIBERA','title'=>'Entrar solo con salida disponible','summary'=>'Evitá detenerte sobre rieles por congestión.','objective'=>'Confirmar espacio suficiente al otro lado antes de entrar al cruce.','indicator'=>'FERROCARRIL.LIBERA','lesson_title'=>'La salida se decide antes de entrar','content'=>'Aunque el control permita avanzar, no se entra si una fila, persona u obstáculo impide liberar completamente las vías. Sobre rieles no se espera, estaciona ni cambia de marcha innecesariamente. Si ocurre una inmovilización, se prioriza salir de la trayectoria y alertar.','scenarios'=>[['Fila detenida','Hay luz favorable, pero no cabe el vehículo después de las vías.','Esperar antes de los rieles hasta disponer de salida completa','Avanzar para que nadie ocupe el espacio','Correcto. El permiso no crea espacio de salida.'],['Objeto cae','Una carga pequeña cae sobre las vías mientras se aproxima una señal activa.','Alejarse y alertar por el canal correspondiente','Regresar a recogerla rápidamente','Correcto. Ningún objeto vale entrar en una trayectoria activa.']],'practice'=>'Explicá con tus palabras la regla “salida antes de entrada” y registrá una transferencia a otra intersección bloqueada.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-021','title'=>'Misión Emociones y Autocontrol Vial','module_code'=>'MISION-AUTOCONTROL-VIAL','module_title'=>'Misión: Pausar antes de reaccionar',
                'description'=>'Aprende a reconocer emociones, presión social y conflictos que pueden alterar decisiones durante la movilidad.',
                'module_summary'=>'Tres retos para detectar el estado personal, resistir presión y desescalar encuentros viales.',
                'objectives'=>'Reconocer señales corporales y emocionales; rechazar retos y presión; aplicar pausas y comunicación que reduzcan conflictos.',
                'prerequisites'=>'Para todas las edades con ejemplos adaptables. No sustituye apoyo profesional en salud mental o manejo de violencia.',
                'competency'=>'AUTOCONTROL-VIAL','competency_title'=>'Regula emociones durante la movilidad','competency_description'=>'Reconoce activación emocional, resiste presión y evita escalar conflictos viales.','subcompetency'=>'AUTOCONTROL.REGULA',
                'prompt'=>'¿Qué respuesta recupera control y evita escalar el riesgo?',
                'units'=>[
                    ['code'=>'EMOCION-RECONOCE','title'=>'El cuerpo avisa','summary'=>'Detectá prisa, enojo, miedo y exceso de confianza.','objective'=>'Identificar estados que reducen atención o aumentan impulsividad.','indicator'=>'AUTOCONTROL.RECONOCE','lesson_title'=>'Sentir no obliga a actuar','content'=>'Mandíbula tensa, respiración rápida, manos rígidas, pensamientos repetitivos o necesidad de “demostrar” algo son señales de activación. Nombrar el estado permite aumentar distancia, reducir decisiones y hacer una pausa antes de actuar.','scenarios'=>[['Llegada tardía','La persona nota tensión y deseo de recuperar tiempo.','Aceptar el retraso, comunicarlo y mantener el margen','Acelerar solo en los tramos conocidos','Correcto. Nombrar la prisa impide convertirla en velocidad.'],['Error ajeno','Otro usuario hace una maniobra que asusta y molesta.','Crear distancia y concentrarse en recuperar estabilidad','Seguirlo para expresar el reclamo','Correcto. La distancia reduce exposición y activación.']],'practice'=>'Construí tu mapa personal: señal corporal, emoción posible, riesgo asociado y acción para recuperar control.'],
                    ['code'=>'EMOCION-PRESION','title'=>'No participar también es valentía','summary'=>'Respondé a retos, burlas y urgencias del grupo.','objective'=>'Rechazar presión social que promueve conductas inseguras.','indicator'=>'AUTOCONTROL.RESISTE','lesson_title'=>'La seguridad no necesita demostraciones','content'=>'Amistades, pasajeros o compañeros pueden presionar para correr, cruzar, competir o usar el teléfono. Una respuesta preparada facilita mantener el límite: nombrar la conducta, decir no y ofrecer una alternativa segura.','scenarios'=>[['Reto en bicicleta','El grupo propone bajar una pendiente compitiendo.','Rechazar la competencia y practicar control en un espacio adecuado','Participar lentamente para no quedar fuera','Correcto. Entrar al reto mantiene la presión y el riesgo.'],['Pasajero insistente','Una persona pide responder un mensaje mientras se conduce.','Pedir que lo gestione o esperar a detenerse','Leerlo en voz alta sin escribir','Correcto. La presión no cambia el requisito de atención.']],'practice'=>'Ensayá tres respuestas breves: “no lo haré”, “esto es lo seguro” y “podemos hacer esta alternativa”.'],
                    ['code'=>'EMOCION-DESESCALA','title'=>'Salir del conflicto','summary'=>'Evitá contacto, competencia y confrontación.','objective'=>'Aplicar estrategias de desescalamiento y pedir ayuda cuando sea necesario.','indicator'=>'AUTOCONTROL.DESESCALA','lesson_title'=>'Ganar una discusión puede perder seguridad','content'=>'Ante agresión se evita responder con gestos, bocina insistente, persecución o bloqueo. Se aumenta distancia, se mantienen puertas o espacio personal seguro y se busca un lugar público o ayuda competente si la amenaza continúa.','scenarios'=>[['Discusión en vía','Otra persona baja de su vehículo gritando.','Evitar confrontar, conservar distancia y retirarse hacia un lugar seguro','Bajar también para explicar quién tuvo razón','Correcto. La prioridad es terminar la exposición, no resolver la discusión.'],['Grupo hostiga','Varias personas siguen a un ciclista y se burlan.','Dirigirse a un sitio seguro y pedir apoyo sin responder al reto','Cambiar la ruta para perseguirlos y grabarlos','Correcto. Buscar protección evita prolongar el encuentro.']],'practice'=>'Creá un plan personal de desescalamiento: señal de inicio, distancia, frase límite, lugar seguro y contacto de apoyo.'],
                ],
            ],
        ];
    }
}
