<?php

declare(strict_types=1);

namespace Database\Seeders;

final class ThirdRoadEducationCoursesSeeder extends NextRoadEducationCoursesSeeder
{
    protected function courses(): array
    {
        return [
            [
                'code'=>'EDU-EXP-016','title'=>'Misión Tecnología y Movilidad Inteligente','module_code'=>'MISION-TECNOLOGIA-MOVIL','module_title'=>'Misión: Usar tecnología sin entregar el criterio',
                'description'=>'Aprende a utilizar mapas, asistentes y datos de movilidad sin distraerte ni obedecer indicaciones inseguras.',
                'module_summary'=>'Tres retos para preparar la tecnología, evaluar sus recomendaciones y proteger los datos personales.',
                'objectives'=>'Configurar dispositivos antes del movimiento; contrastar indicaciones digitales con la realidad; compartir únicamente los datos necesarios.',
                'prerequisites'=>'Aplica a peatones, ciclistas, pasajeros y conductores. Las personas menores usan servicios digitales con acompañamiento responsable.',
                'competency'=>'TECNOLOGIA-MOVIL-SEGURA','competency_title'=>'Usa tecnología de movilidad con criterio','competency_description'=>'Integra herramientas digitales sin perder atención, juicio ni privacidad.','subcompetency'=>'TECNOLOGIA.DECIDE',
                'prompt'=>'¿Qué uso de la tecnología conserva atención, criterio y privacidad?',
                'units'=>[
                    ['code'=>'TEC-PREPARA','title'=>'Configurar antes de moverse','summary'=>'Prepará ruta, sonido y soporte con el vehículo detenido.','objective'=>'Configurar herramientas digitales fuera del movimiento.','indicator'=>'TECNOLOGIA.PREPARA','lesson_title'=>'La pantalla se prepara antes del recorrido','content'=>'La ruta, los avisos y la música se configuran antes de caminar, pedalear o conducir. Si algo requiere atención, se busca un lugar protegido y se detiene completamente. Una persona pasajera puede ayudar, pero quien se mueve conserva la decisión.','scenarios'=>[['Cambio de destino','La aplicación propone una ruta nueva cuando el vehículo ya está en movimiento.','Continuar de forma predecible y revisar solo al detenerse en un lugar permitido','Tomar el teléfono para confirmar rápido','Correcto. La orientación nunca compite con el control del movimiento.'],['Mensaje caminando','Llega un mensaje justo antes de cruzar.','Alejarse del borde, detenerse y resolverlo antes de volver a observar','Responder mientras cambia la señal','Correcto. El cruce comienza con atención libre.']],'practice'=>'Configurá una ruta ficticia antes de salir: destino, volumen, alertas, soporte y lugar seguro para cambios.'],
                    ['code'=>'TEC-CONTRASTA','title'=>'La realidad manda','summary'=>'Compará la recomendación con señales y condiciones presentes.','objective'=>'Rechazar indicaciones digitales incompatibles con la vía real.','indicator'=>'TECNOLOGIA.CONTRASTA','lesson_title'=>'El mapa puede estar desactualizado','content'=>'Una aplicación no ve siempre cierres, inundaciones, controles temporales o restricciones. La señalización, las personas autorizadas y la condición física presente prevalecen. Perder un giro es menos grave que ejecutar una maniobra repentina.','scenarios'=>[['Giro prohibido','El mapa pide girar donde una señal temporal lo prohíbe.','Seguir la señal y permitir que la aplicación recalcule','Girar porque el mapa conoce la ruta','Correcto. La información presente tiene prioridad sobre el dato remoto.'],['Ruta por escaleras','La aplicación ofrece un atajo que no sirve para todo el grupo.','Elegir una alternativa accesible aunque tarde más','Separar al grupo y encontrarse después','Correcto. Una ruta útil debe responder a las necesidades reales.']],'practice'=>'Compará una ruta digital con cinco preguntas: permitido, visible, accesible, protegido y con plan alterno.'],
                    ['code'=>'TEC-PRIVACIDAD','title'=>'Datos que no necesitan viajar','summary'=>'Protegé ubicaciones, rutinas e identidades.','objective'=>'Usar datos de movilidad con consentimiento y mínima exposición.','indicator'=>'TECNOLOGIA.PRIVACIDAD','lesson_title'=>'Compartir ubicación también requiere límites','content'=>'Los recorridos pueden revelar hogar, escuela, horarios y hábitos. Se comparte ubicación solo con personas necesarias, durante el tiempo necesario y mediante un canal apropiado. Las evidencias educativas no incluyen placas, rostros ni coordenadas precisas.','scenarios'=>[['Reto escolar','Una actividad solicita publicar la ruta diaria completa.','Entregar una versión general sin horarios ni puntos identificables','Publicar el recorrido para demostrar que se hizo','Correcto. La evidencia puede existir sin revelar una rutina.'],['Ubicación permanente','Una aplicación conserva acceso a ubicación aunque no se usa ação?','Cambiar el permiso al nivel mínimo necesario y revisarlo periódicamente','Dejarlo activo para evitar configurarlo otra vez','Correcto. El acceso continuo debe tener una necesidad clara.']],'practice'=>'Realizá una auditoría guiada de permisos y escribí tres reglas familiares de ubicación, consentimiento y eliminación.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-017','title'=>'Misión Señales, Prioridades y Acuerdos','module_code'=>'MISION-SENALES-ACUERDOS','module_title'=>'Misión: Comprender la regla y su propósito',
                'description'=>'Interpreta señales y prioridades como un sistema de comunicación que protege y coordina a todas las personas.',
                'module_summary'=>'Tres retos para reconocer familias de señales, resolver prioridades y actuar con prudencia cuando hay duda.',
                'objectives'=>'Distinguir mensajes regulatorios, preventivos e informativos; aplicar prioridades sin competir; responder con seguridad ante información ambigua.',
                'prerequisites'=>'Educación vial general basada en Costa Rica. No sustituye el estudio oficial requerido para obtener una licencia.',
                'competency'=>'COMUNICACION-NORMATIVA','competency_title'=>'Interpreta la comunicación normativa vial','competency_description'=>'Comprende señales, prioridades y controles como acuerdos de convivencia segura.','subcompetency'=>'NORMATIVA.INTERPRETA',
                'prompt'=>'¿Qué decisión respeta el mensaje vial y conserva un margen de seguridad?',
                'units'=>[
                    ['code'=>'SENAL-FAMILIAS','title'=>'Forma, color y ubicación comunican','summary'=>'Reconocé la intención antes de memorizar nombres.','objective'=>'Clasificar señales por función y conducta esperada.','indicator'=>'NORMATIVA.CLASIFICA','lesson_title'=>'Las señales forman un lenguaje','content'=>'Las señales regulatorias establecen obligaciones o prohibiciones; las preventivas anticipan condiciones; las informativas orientan. Marcas viales, semáforos y gestos autorizados completan el sistema. Comprender su propósito ayuda a transferir el aprendizaje a señales nuevas.','scenarios'=>[['Advertencia de curva','Una señal preventiva anuncia una curva que todavía no se ve.','Reducir antes y preparar la trayectoria','Esperar a ver la curva para reaccionar','Correcto. La prevención entrega información anticipada.'],['Marca desgastada','Una línea está poco visible, pero el resto de señales y la geometría indican separación.','Mantener trayectoria prudente y buscar confirmación del conjunto','Ignorar toda organización porque falta pintura','Correcto. Se interpreta el sistema completo sin inventar permiso.']],'practice'=>'Clasificá doce ejemplos cotidianos por función y explicá qué conducta segura intenta producir cada familia.'],
                    ['code'=>'SENAL-PRIORIDAD','title'=>'Prioridad no significa invulnerabilidad','summary'=>'Cedé cuando corresponde y verificá antes de avanzar.','objective'=>'Aplicar prioridades con observación y comunicación.','indicator'=>'NORMATIVA.PRIORIZA','lesson_title'=>'Tener paso no elimina el deber de cuidar','content'=>'La prioridad coordina, pero no garantiza que otra persona haya visto o pueda detenerse. Antes de avanzar se confirma espacio, trayectoria y usuarios vulnerables. Ceder por seguridad no cambia la regla: evita convertir un error ajeno en daño.','scenarios'=>[['Señal favorable','El semáforo cambia, pero una persona aún termina el cruce.','Esperar a que libere la trayectoria','Avanzar para recordarle que cambió la señal','Correcto. La señal autoriza cuando el espacio está efectivamente disponible.'],['Intersección confusa','Dos personas creen tener prioridad y comienzan a avanzar.','Detener la competencia, comunicar y resolver con calma','Acelerar para afirmar la prioridad','Correcto. Renunciar a competir recupera previsibilidad.']],'practice'=>'Representá tres encuentros con roles distintos y explicá regla, riesgo residual y verificación antes de avanzar.'],
                    ['code'=>'SENAL-DUDA','title'=>'Cuando falta información','summary'=>'Reducí y buscá una decisión reversible.','objective'=>'Responder prudentemente ante señales dañadas, controles apagados o instrucciones ambiguas.','indicator'=>'NORMATIVA.DUDA','lesson_title'=>'La duda exige más margen, no más impulso','content'=>'Si una señal está oculta, un semáforo no funciona o las indicaciones parecen contradictorias, se reduce, se observa el conjunto y se evita asumir prioridad. Cuando sea necesario se busca una ruta alternativa o apoyo competente.','scenarios'=>[['Semáforo apagado','Una intersección funciona sin sus luces habituales.','Aproximarse lentamente, aplicar las reglas correspondientes y confirmar cada trayectoria','Cruzar detrás del vehículo anterior sin volver a observar','Correcto. Cada persona debe verificar por sí misma.'],['Señal cubierta','Vegetación impide leer completamente una señal.','Actuar con prudencia y reportar la condición por el canal adecuado','Detenerse en la vía para mover las ramas','Correcto. Se comunica el problema sin exponerse ni alterar infraestructura.']],'practice'=>'Creá un protocolo de cuatro pasos para información dudosa: reducir, observar, confirmar y elegir una acción reversible.'],
                ],
            ],
            [
                'code'=>'EDU-EXP-018','title'=>'Misión Movilidad Laboral Segura','module_code'=>'MISION-MOVILIDAD-LABORAL','module_title'=>'Misión: Trabajar sin normalizar el riesgo vial',
                'description'=>'Prevención para desplazamientos laborales, entregas, visitas y tareas realizadas cerca o dentro de la vía.',
                'module_summary'=>'Tres retos para preparar la jornada, gestionar presión y aprender de incidentes y casi incidentes.',
                'objectives'=>'Planear desplazamientos de trabajo; detener tareas ante presión o fatiga; reportar condiciones para prevenir recurrencias.',
                'prerequisites'=>'Dirigido a personas jóvenes y adultas. No sustituye capacitación ocupacional específica ni procedimientos de la organización.',
                'competency'=>'MOVILIDAD-LABORAL','competency_title'=>'Gestiona el riesgo vial durante el trabajo','competency_description'=>'Planifica, detiene y mejora tareas laborales relacionadas con movilidad.','subcompetency'=>'LABORAL.GESTIONA',
                'prompt'=>'¿Qué decisión protege a la persona sin convertir la presión laboral en riesgo vial?',
                'units'=>[
                    ['code'=>'LABORAL-PLANEA','title'=>'La jornada también es una ruta','summary'=>'Integrá tiempos, vehículo, clima y pausas.','objective'=>'Preparar una jornada móvil con márgenes y responsabilidades claras.','indicator'=>'LABORAL.PLANEA','lesson_title'=>'El tiempo seguro se planifica','content'=>'Una agenda que solo calcula el tiempo ideal empuja a acelerar, omitir revisiones o usar el teléfono. El plan incluye preparación, carga segura, clima, estacionamiento, pausas y retrasos razonables. Ningún incentivo debe depender de conductas inseguras.','scenarios'=>[['Primera entrega','La ruta asignada no contempla revisar la carga ni el vehículo.','Realizar la revisión y comunicar el ajuste necesario','Salir de inmediato para conservar el indicador de tiempo','Correcto. El desempeño comienza con condiciones seguras.'],['Reuniones seguidas','No existe tiempo entre dos visitas en lugares distintos.','Reprogramar o comunicar el retraso antes de iniciar','Recuperar tiempo durante el trayecto','Correcto. La planificación corrige la presión antes de que llegue a la vía.']],'practice'=>'Diseñá una jornada ficticia incluyendo revisión, traslados, estacionamiento, pausas, contactos y margen por cambio climático.'],
                    ['code'=>'LABORAL-DETENTE','title'=>'Autoridad para detener una tarea','summary'=>'Reconocé fatiga, presión y condiciones inseguras.','objective'=>'Interrumpir el trabajo cuando el riesgo supera el control disponible.','indicator'=>'LABORAL.DETIENE','lesson_title'=>'Parar a tiempo es una competencia profesional','content'=>'Somnolencia, enojo intenso, fallas mecánicas, carga inestable o clima severo justifican detenerse en un lugar seguro y comunicar. El café, la ventana abierta o la urgencia no reemplazan descanso ni corrección de la condición.','scenarios'=>[['Somnolencia','La persona pierde fragmentos de recuerdo del último tramo.','Detenerse de forma segura y descansar o solicitar relevo','Subir el volumen y terminar la ruta','Correcto. La pérdida de atención indica que continuar no es controlable.'],['Carga desplazada','Se escucha movimiento de objetos después de una curva.','Detenerse en un lugar protegido y asegurar la carga','Conducir más despacio hasta el destino','Correcto. Una carga inestable puede cambiar el control y lesionar al abrir.']],'practice'=>'Definí cinco criterios de parada y el mensaje breve con el que reportarías cada uno sin temor a represalias.'],
                    ['code'=>'LABORAL-APRENDE','title'=>'Reportar para prevenir','summary'=>'Convertí incidentes y casi incidentes en mejoras.','objective'=>'Registrar hechos y proponer controles sin buscar culpables.','indicator'=>'LABORAL.APRENDE','lesson_title'=>'Un casi incidente es información temprana','content'=>'Una frenada de emergencia sin choque, una ruta imposible o una carga que casi cae muestran una debilidad antes de causar daño. El reporte describe hechos, condiciones y barreras ausentes; protege datos personales y propone seguimiento.','scenarios'=>[['Casi atropello','No hubo lesión y el equipo propone no registrar nada.','Reportar hechos y revisar ruta, horario y visibilidad','Omitirlo porque no produjo daño','Correcto. Aprender antes del daño es prevención efectiva.'],['Error compartido','Varias decisiones contribuyeron a un incidente menor.','Analizar condiciones y controles además de las acciones individuales','Publicar el nombre de quien cometió el último error','Correcto. La mejora sistémica evita repetición sin exposición.']],'practice'=>'Completá un reporte ficticio: hecho, condición, barrera que funcionó, barrera ausente, acción y fecha de revisión.'],
                ],
            ],
        ];
    }
}
